apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-template
  labels:
    app: service-template
spec:
  selector:
    matchLabels:
      app: service-template
  template:
    metadata:
      labels:
        app: service-template
    spec:
      containers:
        - name: service-template
          image: service-template
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 5"]
          ports:
            - containerPort: 9001
          livenessProbe:
            httpGet:
              port: 9001
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 15

          readinessProbe:
            httpGet:
              port: 9001
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 5

          volumeMounts:
            - mountPath: /workspace/config
              name: service-template-config-volume

      volumes:
        - name: service-template-config-volume
          configMap:
            name: service-template-config

      imagePullSecrets:
        - name: regcred
