apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: service-template-config
    files:
      - application.yml
      - app-properties.properties
    options:
      labels:
        app: service-template
