apiVersion: v1
kind: Service
metadata:
  name: service-template
  labels:
    app: service-template
spec:
  selector:
    app: service-template
  ports:
    - port: 80
      targetPort: 9001
      protocol: TCP
  type: ClusterIP
